ustaRestaurant/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ustaRestaurant.Data.Services;
using ustaRestaurant.Data.Static;
using ustaRestaurant.Models;

namespace ustaRestaurant.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductTypeController : Controller
    {
        private readonly IProductTypeService _service;

        public ProductTypeController(IProductTypeService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name")] ProductType productType)
        {
            if (!ModelState.IsValid)
            {
                return View(productType);
            }
            await _service.AddAsync(productType);
            return RedirectToAction(nameof(Index));
        }
        //Get: ProductTypes/Details/1

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var productTypeDetails = await _service.GetByIdAsync(id);

            if (productTypeDetails == null) return View("NotFound");
            return View(productTypeDetails);
        }
        //Get: ProductType/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var productTypeDetails = await _service.GetByIdAsync(id);

            if (productTypeDetails == null) return View("NotFound");
            return View(productTypeDetails);
        }

        //Get: ProductType/Edit/1
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] ProductType productType)
        {
            if (!ModelState.IsValid) return View(productType);
            {
                if (id == productType.Id)
                {
                    await _service.UpdateAsync(id, productType);
                    return RedirectToAction(nameof(Index));
                }

            }
            return View(productType);
        }
        //Get: ProductType/Delete/id
        public async Task<IActionResult> Delete(int id)
        {
            var productTypeDetails = await _service.GetByIdAsync(id);

            if (productTypeDetails == null) return View("NotFound");
            return View(productTypeDetails);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productTypeDetails = await _service.GetByIdAsync(id);
            if (productTypeDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

ustaRestaurant/Views/ProductType/Create.cshtml
@model ProductType
@{
    ViewData["Title"] = "Add a new Product Type";
}
<div class="row text">
    <div class="col-md-8 offset-3">

        <div class="card mt-5 mb-5" style="max-width: 700px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://images.pexels.com/photos/2295285/pexels-photo-2295285.jpeg?auto=compress&cs=tinysrgb&w=600" class="imgCard img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8" style="align-self: center;">
                    <div class="card-body">
                        <h5 class="card-title">Create Product Type</h5>
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-outline-success float-end mt-3" />
                                <a class="btn btn-outline-secondary mt-3" asp-action="Index">Show all</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ustaRestaurant/Views/ProductType/Delete.cshtml
@model ProductType

@{
    ViewData["Title"] = "Delete ProductType";
}

<div class="row text">
    <div class="col-md-8 offset-3">

        <div class="card mt-5 mb-5" style="max-width: 700px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://images.pexels.com/photos/2295285/pexels-photo-2295285.jpeg?auto=compress&cs=tinysrgb&w=600" class="imgCard img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8" style="align-self: center;">
                    <div class="card-body">
                        <h5 class="card-title">Delete Product Type</h5>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="Id" />
                                <input type="submit" value="Confirm" class="btn btn-danger float-end mt-3" />
                            </form>
                            <a class="btn btn-outline-secondary mt-3" asp-action="Index">Show all</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ustaRestaurant/Views/ProductType/Edit.cshtml
@model ProductType
@{
    ViewData["Title"] = "Update Product Type";
}

<div class="row text">
    <div class="col-md-8 offset-3">

        <div class="card mt-5 mb-5" style="max-width: 700px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="https://images.pexels.com/photos/2295285/pexels-photo-2295285.jpeg?auto=compress&cs=tinysrgb&w=600" class="imgCard img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8" style="align-self: center;">
                    <div class="card-body">
                        <h5 class="card-title">Update Product Type</h5>
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Update" class="btn btn-outline-success float-end mt-3" />
                                <a class="btn btn-outline-secondary mt-3" asp-action="Index">Show all</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ustaRestaurant/Views/ProductType/Index.cshtml
@model IEnumerable<ProductType>

@{
    ViewData["Title"] = "Admin of Product Type";
}
<div class="container-fluid">
    <div class="d-flex justify-content-center p-5">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col" width="75%">@Html.DisplayNameFor(mi => mi.Name)</th>
                    <th scope="col" width="25%">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var productType in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(mi => productType.Name)</td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-controller="ProductType" asp-action="Edit" asp-route-id="@productType.Id"><i class="bi bi-pencil-square"></i>&nbsp; Edit</a>
                            <a class="btn btn-danger text-white" asp-controller="ProductType" asp-action="Delete" asp-route-id="@productType.Id"><i class="bi bi-trash-fill"></i>&nbsp; Delete</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>
@await Html.PartialAsync("_CreateItem", "ProductType")